

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cook?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xjr20021107
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8000